
CREATE TABLE IF NOT EXISTS shopping_list (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    product_price DEC(10, 2) NOT NULL,
    category grocery NOT NULL,
    checked BOOLEAN,
    date_added TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

